### ISSUE TITLE
opensource PyReferrer!

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Shopify/pyreferrer#22]
### Why?

It's easy to community maintain this than small teams here at Shopify (it's kinda like open-sourcing the user agent libraries). It's also something I'm sure many other webcompaines have their own (hacky) version of / are looking for one. 

### To Do

From here: https://vault.shopify.com/Open-Source

- [ ] SEO improvements
- [x] get confirmation from John Duff or Jerome
- [x] Add MIT license
- [x] Add a better readme
- [x] open an issue at https://github.com/Shopify/shopify.github.com to add this project to Shopify's open source page. 

cc @Shopify/merchant-optimization @snormore

**Comment by snormore** [comment]
✅ open-sourced
